# Generated by Django 5.1.3 on 2024-12-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_ru',
        ),
    ]
